DELETE FROM Race

DECLARE @RaceId INT

INSERT RACE SELECT 'Risen Star', LTRIM(RTRIM('FG ')) SET @RaceId = @@Identity INSERT LeagueRace (RaceId, Dt, Weight) VALUES(@RaceId, '2/20/2010', 1)
INSERT RACE SELECT 'El Camino Real Derby', LTRIM(RTRIM('GG ')) SET @RaceId = @@Identity INSERT LeagueRace (RaceId, Dt, Weight) VALUES(@RaceId, '2/20/2010', 1)
INSERT RACE SELECT 'Fountain of Youth', LTRIM(RTRIM('GP ')) SET @RaceId = @@Identity INSERT LeagueRace (RaceId, Dt, Weight) VALUES(@RaceId, '2/20/2010', 1)
INSERT RACE SELECT 'Hutchenson', LTRIM(RTRIM('GP ')) SET @RaceId = @@Identity INSERT LeagueRace (RaceId, Dt, Weight) VALUES(@RaceId, '2/20/2010', 1)
INSERT RACE SELECT 'Sham Stakes', LTRIM(RTRIM('SA ')) SET @RaceId = @@Identity INSERT LeagueRace (RaceId, Dt, Weight) VALUES(@RaceId, '2/27/2010', 1)
INSERT RACE SELECT 'Gotham Stakes', LTRIM(RTRIM('AQU ')) SET @RaceId = @@Identity INSERT LeagueRace (RaceId, Dt, Weight) VALUES(@RaceId, '3/6/2010', 1)
INSERT RACE SELECT 'Palm Beach Stakes', LTRIM(RTRIM('GP ')) SET @RaceId = @@Identity INSERT LeagueRace (RaceId, Dt, Weight) VALUES(@RaceId, '3/6/2010', 1)
INSERT RACE SELECT 'Rebel Stakes', LTRIM(RTRIM('OP ')) SET @RaceId = @@Identity INSERT LeagueRace (RaceId, Dt, Weight) VALUES(@RaceId, '3/13/2010', 1)
INSERT RACE SELECT 'San Felipe Stakes', LTRIM(RTRIM('SA ')) SET @RaceId = @@Identity INSERT LeagueRace (RaceId, Dt, Weight) VALUES(@RaceId, '3/13/2010', 1)
INSERT RACE SELECT 'The Tampa Bay Derby', LTRIM(RTRIM('TAM ')) SET @RaceId = @@Identity INSERT LeagueRace (RaceId, Dt, Weight) VALUES(@RaceId, '3/13/2010', 1)
INSERT RACE SELECT 'Florida Derby', LTRIM(RTRIM('GP ')) SET @RaceId = @@Identity INSERT LeagueRace (RaceId, Dt, Weight) VALUES(@RaceId, '3/20/2010', 2)
INSERT RACE SELECT 'Swale Stakes', LTRIM(RTRIM('GP ')) SET @RaceId = @@Identity INSERT LeagueRace (RaceId, Dt, Weight) VALUES(@RaceId, '3/20/2010', 1)
INSERT RACE SELECT 'Louisiana Derby', LTRIM(RTRIM('FG ')) SET @RaceId = @@Identity INSERT LeagueRace (RaceId, Dt, Weight) VALUES(@RaceId, '3/27/2010', 1)
INSERT RACE SELECT 'Lane''s End Stakes', LTRIM(RTRIM('TP ')) SET @RaceId = @@Identity INSERT LeagueRace (RaceId, Dt, Weight) VALUES(@RaceId, '3/27/2010', 1)
INSERT RACE SELECT 'Bay Shore Stakes', LTRIM(RTRIM('AQU ')) SET @RaceId = @@Identity INSERT LeagueRace (RaceId, Dt, Weight) VALUES(@RaceId, '4/3/2010', 1)
INSERT RACE SELECT 'Wood Memorial Stakes', LTRIM(RTRIM('AQU ')) SET @RaceId = @@Identity INSERT LeagueRace (RaceId, Dt, Weight) VALUES(@RaceId, '4/3/2010', 2)
INSERT RACE SELECT 'Illinois Derby', LTRIM(RTRIM('HAW ')) SET @RaceId = @@Identity INSERT LeagueRace (RaceId, Dt, Weight) VALUES(@RaceId, '4/3/2010', 1)
INSERT RACE SELECT 'Santa Anita Derby', LTRIM(RTRIM('SA ')) SET @RaceId = @@Identity INSERT LeagueRace (RaceId, Dt, Weight) VALUES(@RaceId, '4/3/2010', 2)
INSERT RACE SELECT 'Blue Grass Stakes', LTRIM(RTRIM('KEE ')) SET @RaceId = @@Identity INSERT LeagueRace (RaceId, Dt, Weight) VALUES(@RaceId, '4/10/2010', 2)
INSERT RACE SELECT 'Arkansas Derby', LTRIM(RTRIM('OP ')) SET @RaceId = @@Identity INSERT LeagueRace (RaceId, Dt, Weight) VALUES(@RaceId, '4/10/2010', 2)
INSERT RACE SELECT 'Coolmore Lexington Stakes', LTRIM(RTRIM('KEE ')) SET @RaceId = @@Identity INSERT LeagueRace (RaceId, Dt, Weight) VALUES(@RaceId, '4/17/2010', 1)
INSERT RACE SELECT 'Withers Stakes', LTRIM(RTRIM('AQU ')) SET @RaceId = @@Identity INSERT LeagueRace (RaceId, Dt, Weight) VALUES(@RaceId, '4/24/2010', 1)
INSERT RACE SELECT 'Cliff''s Edge Derby Trial', LTRIM(RTRIM('CD ')) SET @RaceId = @@Identity INSERT LeagueRace (RaceId, Dt, Weight) VALUES(@RaceId, '4/24/2010', 1)
INSERT RACE SELECT 'Kentucky Derby', LTRIM(RTRIM('CD ')) SET @RaceId = @@Identity INSERT LeagueRace (RaceId, Dt, Weight) VALUES(@RaceId, '5/1/2010', 4)
INSERT RACE SELECT 'Preakness Stakes', LTRIM(RTRIM('PIM')) SET @RaceId = @@Identity INSERT LeagueRace (RaceId, Dt, Weight) VALUES(@RaceId, '5/15/2010', 3)
INSERT RACE SELECT 'Belmont Stakes', LTRIM(RTRIM('BEL')) SET @RaceId = @@Identity INSERT LeagueRace (RaceId, Dt, Weight) VALUES(@RaceId, '6/5/2010', 3)
