BEGIN TRANSACTION

DELETE FROM ReportLeagueRaceBet
DELETE FROM UserStandings
DELETE FROM UserRaceDetail
DELETE FROM UserDue
DELETE FROM RaceDetailPayout
DELETE FROM RaceDetails
DELETE FROM LeagueRace
DELETE FROM Race

IF @@ERROR <> 0 
	BEGIN
		ROLLBACK TRANSACTION
	END
ELSE
	BEGIN
		COMMIT TRANSACTION
	END