<?xml version="1.0" encoding="utf-8"?>
<Database Name="HRLeague" Class="HorseLeagueDAODataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LOOSEY;Initial Catalog=HRLeague;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="HRLeagueConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.UserDue" Member="UserDues">
    <Type Name="UserDue">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Yr" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HasPaid" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_User_UserDue" Member="aspnet_User" ThisKey="UserId" Type="aspnet_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LeagueRace" Member="LeagueRaces">
    <Type Name="LeagueRace">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RaceId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Dt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PostTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FormUrl" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Association Name="LeagueRace_RaceDetail" Member="RaceDetails" OtherKey="LeagueRaceId" Type="RaceDetail" />
      <Association Name="LeagueRace_UserRaceDetail" Member="UserRaceDetails" OtherKey="LeagueRaceId" Type="UserRaceDetail" />
      <Association Name="LeagueRace_RaceDetailPayout" Member="RaceDetailPayouts" OtherKey="LeagueRaceId" Type="RaceDetailPayout" />
      <Association Name="Race_LeagueRace" Member="Race" ThisKey="RaceId" Type="Race" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Race" Member="Races">
    <Type Name="Race">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Track" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Race_LeagueRace" Member="LeagueRaces" OtherKey="RaceId" Type="LeagueRace" />
    </Type>
  </Table>
  <Table Name="dbo.RaceDetails" Member="RaceDetails">
    <Type Name="RaceDetail">
      <Column Name="RaceDetailId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LeagueRaceId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HorseId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PostPosition" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsScratched" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OddsOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="RaceDetail_UserRaceDetail" Member="UserRaceDetails" OtherKey="RaceDetailId" Type="UserRaceDetail" />
      <Association Name="RaceDetail_RaceDetailPayout" Member="RaceDetailPayout" OtherKey="RaceDetailId" Type="RaceDetailPayout" Cardinality="One" />
      <Association Name="RaceDetail_ReportLeagueRaceBet" Member="ReportLeagueRaceBets" OtherKey="RaceDetailId" Type="ReportLeagueRaceBet" />
      <Association Name="LeagueRace_RaceDetail" Member="LeagueRace" ThisKey="LeagueRaceId" Type="LeagueRace" IsForeignKey="true" />
      <Association Name="Horse_RaceDetail" Member="Horse" ThisKey="HorseId" Type="Horse" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserRaceDetail" Member="UserRaceDetails">
    <Type Name="UserRaceDetail">
      <Column Name="RaceDetailId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LeagueRaceId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BetType" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="LeagueRace_UserRaceDetail" Member="LeagueRace" ThisKey="LeagueRaceId" Type="LeagueRace" IsForeignKey="true" />
      <Association Name="RaceDetail_UserRaceDetail" Member="RaceDetail" ThisKey="RaceDetailId" Type="RaceDetail" IsForeignKey="true" />
      <Association Name="aspnet_User_UserRaceDetail" Member="aspnet_User" ThisKey="UserId" Type="aspnet_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Users" Member="aspnet_Users">
    <Type Name="aspnet_User">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredUserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="MobileAlias" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="IsAnonymous" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastActivityDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_User_UserDue" Member="UserDues" OtherKey="UserId" Type="UserDue" />
      <Association Name="aspnet_User_UserRaceDetail" Member="UserRaceDetails" OtherKey="UserId" Type="UserRaceDetail" />
      <Association Name="aspnet_User_UserStanding" Member="UserStandings" OtherKey="UserId" Type="UserStanding" />
    </Type>
  </Table>
  <Table Name="dbo.RaceDetailPayout" Member="RaceDetailPayouts">
    <Type Name="RaceDetailPayout">
      <Column Name="RaceDetailId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LeagueRaceId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BetType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WinAmount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PlaceAmount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ShowAmount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="LeagueRace_RaceDetailPayout" Member="LeagueRace" ThisKey="LeagueRaceId" Type="LeagueRace" IsForeignKey="true" />
      <Association Name="RaceDetail_RaceDetailPayout" Member="RaceDetail" ThisKey="RaceDetailId" Type="RaceDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Horse" Member="Horses">
    <Type Name="Horse">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Horse_RaceDetail" Member="RaceDetails" OtherKey="HorseId" Type="RaceDetail" />
    </Type>
  </Table>
  <Table Name="dbo.ReportLeagueRaceBet" Member="ReportLeagueRaceBets">
    <Type Name="ReportLeagueRaceBet">
      <Column Name="RaceDetailId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BetType" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserBetCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="RaceDetail_ReportLeagueRaceBet" Member="RaceDetail" ThisKey="RaceDetailId" Type="RaceDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserStandings" Member="UserStandings">
    <Type Name="UserStanding">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Yr" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="WinWinPct" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="WinPlacePct" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="WinShowPct" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="PlacePlacePct" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="PlaceShowPct" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ShowShowPct" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="WinWinAvg" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="WinPlaceAvg" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="WinShowAvg" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="PlacePlaceAvg" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="PlaceShowAvg" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ShowShowAvg" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="WinFavPct" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ROI" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_User_UserStanding" Member="aspnet_User" ThisKey="UserId" Type="aspnet_User" IsForeignKey="true" />
    </Type>
  </Table>
</Database>